#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x15CDDA6AE19135A2 (srk@debian.org)
#
Name     : dnsmasq
Version  : 2.80
Release  : 40
URL      : http://www.thekelleys.org.uk/dnsmasq/dnsmasq-2.80.tar.xz
Source0  : http://www.thekelleys.org.uk/dnsmasq/dnsmasq-2.80.tar.xz
Source1  : dnsmasq.service
Source99 : http://www.thekelleys.org.uk/dnsmasq/dnsmasq-2.80.tar.xz.asc
Summary  : A lightweight caching nameserver
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: dnsmasq-bin = %{version}-%{release}
Requires: dnsmasq-config = %{version}-%{release}
Requires: dnsmasq-data = %{version}-%{release}
Requires: dnsmasq-license = %{version}-%{release}
Requires: dnsmasq-man = %{version}-%{release}
Patch1: stateless.patch
Patch2: cve-2015-3294.nopatch
Patch3: nov6.patch
Patch4: build.patch

%description
Dnsmasq is lightweight, easy to configure DNS forwarder and DHCP server. It 
is designed to provide DNS and, optionally, DHCP, to a small network. It can
serve the names of local machines which are not in the global DNS. The DHCP 
server integrates with the DNS server and allows machines with DHCP-allocated
addresses to appear in the DNS with names configured either in each host or 
in a central configuration file. Dnsmasq supports static and dynamic DHCP 
leases and BOOTP for network booting of diskless machines.

%package bin
Summary: bin components for the dnsmasq package.
Group: Binaries
Requires: dnsmasq-data = %{version}-%{release}
Requires: dnsmasq-config = %{version}-%{release}
Requires: dnsmasq-license = %{version}-%{release}
Requires: dnsmasq-man = %{version}-%{release}

%description bin
bin components for the dnsmasq package.


%package config
Summary: config components for the dnsmasq package.
Group: Default

%description config
config components for the dnsmasq package.


%package data
Summary: data components for the dnsmasq package.
Group: Data

%description data
data components for the dnsmasq package.


%package license
Summary: license components for the dnsmasq package.
Group: Default

%description license
license components for the dnsmasq package.


%package man
Summary: man components for the dnsmasq package.
Group: Default

%description man
man components for the dnsmasq package.


%prep
%setup -q -n dnsmasq-2.80
%patch1 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539933347
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1539933347
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dnsmasq
cp COPYING %{buildroot}/usr/share/package-licenses/dnsmasq/COPYING
cp COPYING-v3 %{buildroot}/usr/share/package-licenses/dnsmasq/COPYING-v3
%make_install PREFIX=%{_prefix}
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/dnsmasq.service
## install_append content
install -d %{buildroot}%{_bindir}
install -d %{buildroot}%{_mandir}/man1
install -d %{buildroot}%{_libdir}/systemd/system/
install -D dnsmasq.conf.example %{buildroot}%{_datadir}/defaults/dnsmasq/dnsmasq.conf
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dnsmasq

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/dnsmasq.service

%files data
%defattr(-,root,root,-)
/usr/share/defaults/dnsmasq/dnsmasq.conf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dnsmasq/COPYING
/usr/share/package-licenses/dnsmasq/COPYING-v3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/dnsmasq.8
